### ISSUE TITLE
Insights | Interesting times produce creative opportunities | content tweaks

### ISSUE THREAD

**Issue by vickimcfadden** [GSA/wp2030-microsite-new#29]
(overall comment, text seems squeezed to the left rather than taking up the whole screen)

By Chuck Hardy `remove space` , Chief Architect

“The stone age didn’t end because we ran out of stones. It ended because better technologies were developed”  `remove bold for Don's attribution` attributed to Don Huberts

10 percent technology, 90 percent sociology `this is a header, remove italics and make it a H1/2/3 ... whatever`

GSA’s Center for Workplace Strategy is exploring the convergence of technology, conversation, and people in our `forthcoming - remove this word, it will be live when we launch` Workplace Innovation Lab. This `will be - sub will be for is` a space where industry partners try out leading-edge offerings in furniture

Workplace is about bringing together the right people for the right conversation `this is a header, remove italics and make it a H1/2/3 ... whatever`

**Comment by JessicaMarine1** [comment]
@vickimcfadden I'm moving this to `Done` but want you to take a second look at the treatment of the "headers" throughout the articles. Do they seem a little big to you? May want to review for all

**Comment by actuallyjenn** [comment]
spoke to wei on this page and we're reopening this ticket with the following requested changes:

- [ ] following quotes should actually be h2 headings:
   - “May you live in interesting times.”
   - “I never created anything, I just remembered things differently.”

- [ ] following quote should be in a quote box:
   -  “The stone age didn’t end because we ran out of stones. It ended because better technologies were developed” —attributed to Don Huberts
